---
- name: Create OSP User
  hosts: all
  gather_facts: False
  tasks:
    - name: Create OSP User
      openstack.cloud.identity_user:
        state: present
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        email: "{{ user_email }}"
        default_project: "{{ project }}"
