---
- name: Create OSP Flavor
  hosts: all
  gather_facts: False
  tasks:
    - name: Create a flavor
      openstack.cloud.compute_flavor:
        state: present
        name: "{{ flavor_name }}"
        ram: "{{ flavor_ram }}"
        vcpus: "{{ flavor_cpus }}"
        disk: "{{ flavor_disk_space_gb }}"
        ephemeral: "{{ flavor_ephemeral_space_gb }}"
        description: "{{ flavor_description }}"
      
