---
- name: Create a OSP User
  hosts: all
  gather_facts: False
  tasks:
    - name: Create OSP User
      openstack.cloud.identity_user:
        state: present
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        email: "{{ user_email }}"
        domain: "{{ domain_id }}"
        default_project: "{{ project }}"
        validate_certs: false
      register: osp_user
      
    - debug: 
      var: osp_user
