---
- name: DELETE a OSP Keypair
  hosts: all
  gather_facts: False
  tasks:
    - name: DELETE a keypair in OpenStack
      openstack.cloud.keypair:
        name: "{{ keypair_name }}"
        state: absent
