---
- name: Create Instance
  hosts: all
  gather_facts: False
  tasks:        
    - name: Create a new instance and attaches to a network and passes metadata to the instance
      openstack.cloud.server:
        state: present
        verify: no
        name: "{{ instance_name }}"
        image: 	"{{ image_name }}"
        key_name: "{{ keypair_name }}"
        timeout: 200
        flavor: "{{ flavor_name }}"
        security_groups:
          - "{{ secgroup_name }}"
        network: "{{ private_subnet_name }}"
        meta:
          hostname: "{{ instance_hostname }}"

    - name: Create and assign floating IP
      openstack.cloud.floating_ip:
        server: "{{ instance_name }}"
