---
- name: Create OSP Project
  hosts: all
  gather_facts: False   
  tasks:
    - name: Create OSP Project
      openstack.cloud.project:
        state: present
        name: "{{ project }}"
        description: "{{ project_description }}"
        is_enabled: True
        wait: yes
        region_name: "{{ region_name }}"
        interface: public
        domain: "{{ domain_id }}"
        validate_certs: false
