---
- name: Create a OSP User
  hosts: all
  gather_facts: False
  tasks:
    - name: Create OSP User
      openstack.cloud.identity_user:
        state: present
        name: "{{ openstack_user_name }}"
        password: "{{ openstack_user_password }}"
        email: "{{ openstack_user_email }}"
        cloud: "{{ openstack_cloud }}"
        domain: "{{ openstack_domain_id }}"
        default_project: "{{ openstack_project }}"
        validate_certs: false
      register: osp_user
      
    - debug: 
      var: osp_user
