---
- name: Create OSP Security Group
  hosts: all
  gather_facts: False
  tasks:
    - name: Create a security group rule
      openstack.cloud.security_group_rule:
        security_group: "{{ secgroup_name }}"
        protocol: "{{ protocol }}"
        port_range_min: "{{ port_range_min }}"
        port_range_max: "{{ port_range_max }}"
        remote_ip_prefix: "{{ remote_ip_prefix }}"
        state: present
