---
- name: Create OSP Image
  hosts: all
  gather_facts: False
  tasks:
    - name: Upload an image from a URL
      openstack.cloud.image:
        name: "{{ image_name }}"
        container_format: bare
        disk_format: "{{ image_disk_format }}"
        state: present
        filename: "{{ image_url_file }}"
        is_public: true
