---
- name: Create a OSP Keypair
  hosts: all
  gather_facts: False
  tasks:
    - name: Create a keypair in OpenStack
      openstack.cloud.keypair:
        name: "{{ openstack_keypair_name }}"
        state: present
      register: keypair
