---
- name: DELETE OSP Security Group
  hosts: all
  gather_facts: False
  tasks:
    - name: DELETE a security group
      openstack.cloud.security_group:
        security_group: "{{ secgroup_name }}"
        state: absent
        
