---
- name: Create OSP Project
  hosts: all
  gather_facts: False   
  tasks:
    - name: Create OSP Project
      openstack.cloud.project:
        name: "{{ project }}"
        description: "{{ project_description }}"
        is_enabled: true
        wait: yes
        state: present
