---
- name: Create Instance
  hosts: all
  gather_facts: False
  tasks:        
    - name: Create a new instance and attaches to a network and passes metadata to the instance
      openstack.cloud.server:
        state: present
        verify: no
        name: "{{ instance_name }}"
        image: 	"{{ image_name }}"
        key_name: "{{ key_name }}"
        timeout: 200
        flavor: "{{ flavor_name }}"
        security_groups:
          - "{{ secgroup_name }}"
        nics:
          - net-id: "{{ net_id }}"
          - net-name: "{{ net_name }}"
        meta:
          hostname: "{{ hostname }}"
