---
- name: Create a OSP Project
  hosts: all
  gather_facts: False   
  tasks:
    - name: Create OSP Project
      openstack.cloud.project:
        state: present
        name: "{{ openstack_project }}"
        description: "{{ openstack_project_description }}"
        is_enabled: True
        wait: yes
        region_name: "{{ openstack_region_name }}"
        interface: public
        domain: "{{ openstack_domain_id }}"
        validate_certs: false
