---
- name: Create OSP Image
  hosts: all
  gather_facts: False
  tasks:
    - name: Download file and force basic auth
      ansible.builtin.get_url:
        url: "{{ image_url_file }}"
        dest: /tmp
      register: image

    - name: Print return information from the previous task
       ansible.builtin.debug:
         var: image

      
