---
- name: Create Instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
        
   - name: Create a new instance and attaches to a network and passes metadata to the instance
     os_server:
        state: present
        cloud: devstack
        verify: no
        name: vmtest
        image: 	RHEL-7
        key_name: test-drive
        timeout: 200
        flavor: m1.small
        nics:
         - net-name: private
        meta:
           hostname: test
