---
- name: Copy HelloWorld WAR file to host
  copy: src=jboss-helloworld.war dest=/tmp

- name: Deploy HelloWorld App to JBoss
  jboss: deploy_path=/usr/share/jboss-as/standalone/deployments/ src=/tmp/jboss-helloworld.war deployment=helloworld.war state=present
  
- name: Copy Ticket Monster WAR file to host
  copy: src=ticket-monster.war dest=/tmp

- name: Deploy Ticket Monster App to JBoss
  jboss: deploy_path=/usr/share/jboss-as/standalone/deployments/ src=/tmp/ticket-monster.war deployment=ticket-monster.war state=present
  
- name: Restart JBoss
  service: name=jboss state=restarted
